### ISSUE TITLE
Missing instructions in README

### ISSUE THREAD

**Issue by brunoborges** [oracle/bdglue#1]
Hi,

README says I should have GG for Big Data installed. Would be nice to have a link to the download page and quick instructions on how to install it.

**Comment by thomasvengal** [comment]
Oracle GoldenGate for Big Data can be download from the following 2 locations
1) OTN : http://www.oracle.com/technetwork/middleware/goldengate/downloads/index.html
2) Oracle Support Website ; http://support.oracle.com (note that you need to have valid login credentials)

**Comment by brunoborges** [comment]
Thanks @thomasvengal. Is it possible to add this information in the [README.md](https://github.com/oracle/bdglue/tree/master/README.md) ?

**Comment by thomasvengal** [comment]
Yes, that was done.

 

Thanks,

Thomas
